{
 "title": "Komidinhas",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "TPS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "TPS máximo",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "irate(login_operation_duration_seconds_count{uri=\"/auth/login\"}[1m])"
    }
   ]
  },
  {
   "title": "TPS atual",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(login_operation_duration_seconds_count{uri=\"/auth/login\"}[1m])"
    }
   ]
  },
  {
   "title": "Histórico de TPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "irate(login_operation_duration_seconds_count{uri=\"/auth/login\"}[1m])"
    }
   ]
  },
  { "title": "Percentis ao longo do tempo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Percentis máximos",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(login_operation_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(login_operation_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(login_operation_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(login_operation_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Percentis ao longo do tempo",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 17, "x": 7, "y": 21 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(login_operation_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(login_operation_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(login_operation_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(login_operation_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "0.9"
    }
   ]
  }
 ]
}